apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: "$(IMAGE_NAME)"  # Reference the variable from the ConfigMap - "${DOCKER_USERNAME}/fastapi-redis:latest"
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis-service
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
